### PR TITLE
Added textInput ref

### PR DESCRIPTION
**Pull request by hanyoureal**
Added a ref to the textInput to be able to access the .focus() method of the textInput

### CODE REVIEW

**Comment by hanyoureal** [comment]
@vishaljadav24

**Comment by vishaljadav24** [comment]
@hanyoureal This is not a major change for this repo. If you want some modification which is required in your project you can use my repo as a reference. Do change which is useful for all user not only for you.

**Comment by vishaljadav24** [comment]
@hanyoureal By your change, I can not get my component reference in other class where I used component.

**Comment by hanyoureal** [comment]
Thanks for your reply.
How can I ref the input in order to focus it automatically after completing a previous input? From the example in this repo I can not figure out.
Thanks

**Pull request closed without merging**
